In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("All libraries working. Day 1 complete.")

All libraries working. Day 1 complete.


In [17]:
# This is the most important block today
# You are now reading, cleaning and analyzing document data
# exactly like a real AI pipeline does

df = pd.read_csv("documents.csv")

# Clean the text — lowercase everything
df["clean_text"] = df["text"].str.lower()

# Remove punctuation
df["clean_text"] = df["clean_text"].str.replace("[^a-z\s]", "", regex=True)

# Count words in each document
df["word_count"] = df["clean_text"].apply(lambda x: len(x.split()))

# Find the document with most words
most_words = df.loc[df["word_count"].idxmax()]
print("Document with most words:")
print(most_words["text"])
print("Word count:", most_words["word_count"])

print("\nFull cleaned dataset:")
print(df[["document_id", "clean_text", "word_count", "category"]])

Document with most words:
Deep learning is a subset of machine learning
Word count: 8

Full cleaned dataset:
   document_id                                         clean_text  word_count  \
0            1          ai is transforming healthcare and finance           6   
1            2    python is the most popular programming language           7   
2            3     machine learning models require large datasets           6   
3            4      deep learning is a subset of machine learning           8   
4            5  australia is investing in artificial intelligence           6   

      category  
0   technology  
1  programming  
2           AI  
3           AI  
4   technology  


In [18]:
# GroupBy is extremely powerful
# It lets you summarize data by category
# You will use this constantly in data analysis

df = pd.read_csv("documents.csv")

# Average word count per category
grouped = df.groupby("category")["word_count"].mean()
print("Average word count per category:\n", grouped)

# Count how many documents per category
count_per_category = df.groupby("category")["document_id"].count()
print("\nDocuments per category:\n", count_per_category)

Average word count per category:
 category
AI             6.5
programming    7.0
technology     6.0
Name: word_count, dtype: float64

Documents per category:
 category
AI             2
programming    1
technology     2
Name: document_id, dtype: int64


In [19]:
df = pd.read_csv("documents.csv")

# Add a new column — length of each text
df["text_length"] = df["text"].apply(len)

# Add another column — whether text mentions AI
df["mentions_AI"] = df["text"].str.contains("AI|artificial intelligence", case=False)

print(df[["text", "text_length", "mentions_AI"]])

                                                text  text_length  mentions_AI
0          AI is transforming healthcare and finance           41         True
1    Python is the most popular programming language           47        False
2     Machine learning models require large datasets           46        False
3      Deep learning is a subset of machine learning           45        False
4  Australia is investing in artificial intelligence           49         True


In [20]:
# Real world data is always messy
# Missing values are one of the most common problems

# Create a messy dataset with missing values
messy_data = {
    "word": ["AI", "Python", None, "learning", "data", None],
    "count": [3, 2, 1, None, 4, 2],
    "category": ["tech", "programming", "tech", "AI", None, "AI"]
}

df_messy = pd.DataFrame(messy_data)
print("Before cleaning:\n", df_messy)
print("\nMissing values:\n", df_messy.isnull().sum())

# Drop rows with any missing values
df_clean = df_messy.dropna()
print("\nAfter dropping missing rows:\n", df_clean)

# OR fill missing values instead of dropping
df_filled = df_messy.fillna("unknown")
print("\nAfter filling missing values:\n", df_filled)

Before cleaning:
        word  count     category
0        AI    3.0         tech
1    Python    2.0  programming
2       NaN    1.0         tech
3  learning    NaN           AI
4      data    4.0          NaN
5       NaN    2.0           AI

Missing values:
 word        2
count       1
category    1
dtype: int64

After dropping missing rows:
      word  count     category
0      AI    3.0         tech
1  Python    2.0  programming

After filling missing values:
        word    count     category
0        AI      3.0         tech
1    Python      2.0  programming
2   unknown      1.0         tech
3  learning  unknown           AI
4      data      4.0      unknown
5   unknown      2.0           AI


In [21]:
# This is how you will read real documents in your project
df = pd.read_csv("documents.csv")

print("Shape:", df.shape)
print("\nFirst few rows:")
print(df.head())
print("\nColumn info:")
print(df.info())

Shape: (5, 4)

First few rows:
   document_id                                               text  \
0            1          AI is transforming healthcare and finance   
1            2    Python is the most popular programming language   
2            3     Machine learning models require large datasets   
3            4      Deep learning is a subset of machine learning   
4            5  Australia is investing in artificial intelligence   

      category  word_count  
0   technology           6  
1  programming           7  
2           AI           6  
3           AI           7  
4   technology           6  

Column info:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   document_id  5 non-null      int64
 1   text         5 non-null      str  
 2   category     5 non-null      str  
 3   word_count   5 non-null      int64
dtypes: int64(2), str(2)
memory usage

In [22]:
import pandas as pd

# Create a fake dataset and save it as CSV
# This simulates what reading a real document dataset looks like

data = {
    "document_id": [1, 2, 3, 4, 5],
    "text": [
        "AI is transforming healthcare and finance",
        "Python is the most popular programming language",
        "Machine learning models require large datasets",
        "Deep learning is a subset of machine learning",
        "Australia is investing in artificial intelligence"
    ],
    "category": ["technology", "programming", "AI", "AI", "technology"],
    "word_count": [6, 7, 6, 7, 6]
}

df = pd.DataFrame(data)

# Save it as a CSV file
df.to_csv("documents.csv", index=False)
print("CSV file created successfully")
print(df)

CSV file created successfully
   document_id                                               text  \
0            1          AI is transforming healthcare and finance   
1            2    Python is the most popular programming language   
2            3     Machine learning models require large datasets   
3            4      Deep learning is a subset of machine learning   
4            5  Australia is investing in artificial intelligence   

      category  word_count  
0   technology           6  
1  programming           7  
2           AI           6  
3           AI           7  
4   technology           6  


In [23]:
# These are the commands you will use every single day
# Always run these first when you get any new data

print("Shape:", df.shape)           # rows and columns
print("\nColumn names:", df.columns.tolist())
print("\nData types:\n", df.dtypes)
print("\nBasic stats:\n", df.describe())
print("\nFirst 3 rows:\n", df.head(3))

Shape: (5, 4)

Column names: ['document_id', 'text', 'category', 'word_count']

Data types:
 document_id    int64
text             str
category         str
word_count     int64
dtype: object

Basic stats:
        document_id  word_count
count     5.000000    5.000000
mean      3.000000    6.400000
std       1.581139    0.547723
min       1.000000    6.000000
25%       2.000000    6.000000
50%       3.000000    6.000000
75%       4.000000    7.000000
max       5.000000    7.000000

First 3 rows:
    document_id                                             text     category  \
0            1        AI is transforming healthcare and finance   technology   
1            2  Python is the most popular programming language  programming   
2            3   Machine learning models require large datasets           AI   

   word_count  
0           6  
1           7  
2           6  


In [24]:
# Filtering means finding only the rows you care about
# Like searching for specific words in a document

# Show only words that appear more than once
frequent_words = df[df["count"] > 1]
print("Words appearing more than once:\n", frequent_words)

# Sort by count — highest first
sorted_df = df.sort_values("count", ascending=False)
print("\nSorted by frequency:\n", sorted_df)

KeyError: 'count'

In [ ]:
# Now combine everything — NumPy + Pandas together
# This is exactly how your Document Assistant will process text

document_text = """
AI is transforming the world. Python is the language of AI.
Machine learning is a subset of AI. Deep learning is powerful.
Australia needs more AI engineers. Python developers are in demand.
"""

# Step 1 - split into words and clean
words = document_text.lower().replace(".", "").replace(",", "").split()

# Step 2 - count frequencies
word_count = {}
for word in words:
    word_count[word] = word_count.get(word, 0) + 1

# Step 3 - put into a DataFrame
df_doc = pd.DataFrame(list(word_count.items()), columns=["word", "count"])

# Step 4 - sort by most frequent
df_doc = df_doc.sort_values("count", ascending=False)

print("Top 10 most frequent words:\n")
print(df_doc.head(10))

Top 10 most frequent words:

           word  count
0            ai      4
1            is      4
3           the      2
5        python      2
9      learning      2
7            of      2
4         world      1
2  transforming      1
6      language      1
8       machine      1


In [ ]:
import pandas as pd

# A DataFrame is like an Excel table in Python
# This is how we will store and analyze document data

data = {
    "word": ["AI", "Python", "future", "language", "learning"],
    "count": [3, 2, 1, 1, 2],
    "length": [2, 6, 6, 8, 8]
}

df = pd.DataFrame(data)
print(df)

       word  count  length
0        AI      3       2
1    Python      2       6
2    future      1       6
3  language      1       8
4  learning      2       8


In [ ]:
import numpy as np

# Slicing means grabbing specific parts of an array
# Just like grabbing specific words from a document

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Full array:", arr)
print("First 3 elements:", arr[:3])
print("Last 3 elements:", arr[-3:])
print("Middle elements:", arr[2:6])
print("Every 2nd element:", arr[::2])

Full array: [ 10  20  30  40  50  60  70  80  90 100]
First 3 elements: [10 20 30]
Last 3 elements: [ 80  90 100]
Middle elements: [30 40 50 60]
Every 2nd element: [10 30 50 70 90]


In [ ]:
# 2D arrays are like tables — rows and columns
# AI models store data exactly like this internally

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Full matrix:\n", matrix)
print("Shape:", matrix.shape)        # how many rows and columns
print("First row:", matrix[0])
print("Second column:", matrix[:, 1])
print("Single element row 1 col 2:", matrix[0][1])

Full matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
First row: [1 2 3]
Second column: [2 5 8]
Single element row 1 col 2: 2


In [ ]:
# These operations are what AI uses to process data
# When AI reads your document, it does math like this on millions of numbers

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Add:", a + b)
print("Multiply:", a * b)
print("Square root:", np.sqrt(b))
print("Sum of all:", np.sum(b))
print("Mean:", np.mean(b))
print("Standard deviation:", np.std(b))

Add: [11 22 33 44 55]
Multiply: [ 10  40  90 160 250]
Square root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Sum of all: 150
Mean: 30.0
Standard deviation: 14.142135623730951


In [ ]:
# A document is just a collection of words
# Lists and dictionaries are how we store and count them

sentence = "AI is the future and Python is the language of AI"

# Convert sentence into a list of words
words = sentence.split()
print("All words:", words)
print("Total words:", len(words))
print("Unique words:", len(set(words)))

All words: ['AI', 'is', 'the', 'future', 'and', 'Python', 'is', 'the', 'language', 'of', 'AI']
Total words: 11
Unique words: 8


In [ ]:
# Count how many times each word appears
word_count = {}

for word in words:
    if word in word_count:
        word_count[word] += 1
    else:
        word_count[word] = 1

print(word_count)

{'AI': 2, 'is': 2, 'the': 2, 'future': 1, 'and': 1, 'Python': 1, 'language': 1, 'of': 1}


In [ ]:
import numpy as np

# Convert counts into a NumPy array
counts = np.array(list(word_count.values()))
labels = np.array(list(word_count.keys()))

print("Words:", labels)
print("Counts:", counts)
print("Most repeated word appears:", np.max(counts), "times")
print("Average frequency:", np.mean(counts))

Words: ['AI' 'is' 'the' 'future' 'and' 'Python' 'language' 'of']
Counts: [2 2 2 1 1 1 1 1]
Most repeated word appears: 2 times
Average frequency: 1.375


In [ ]:
# NumPy makes math on arrays super fast
numbers = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Max:", np.max(numbers))
print("Min:", np.min(numbers))

# Multiply every number by 2 in one line — no loop needed
print("Doubled:", numbers * 2)

Sum: 150
Mean: 30.0
Max: 50
Min: 10
Doubled: [ 20  40  60  80 100]


In [ ]:
# This is the foundation of your AI Document Assistant
# Right now we are manually typing the text
# In Week 3 this will read a real PDF file automatically

document_text = """
Artificial intelligence is transforming the world. 
Python is the most popular language for AI development.
Machine learning and deep learning are subsets of AI.
Australia is investing heavily in AI and technology.
"""

words = document_text.lower().split()
print("Document has", len(words), "words")
print("Unique words:", len(set(words)))

Document has 32 words
Unique words: 26
