In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("All libraries working. Day 1 complete.")

All libraries working. Day 1 complete.


In [ ]:
# These are the commands you will use every single day
# Always run these first when you get any new data

print("Shape:", df.shape)           # rows and columns
print("\nColumn names:", df.columns.tolist())
print("\nData types:\n", df.dtypes)
print("\nBasic stats:\n", df.describe())
print("\nFirst 3 rows:\n", df.head(3))

Shape: (5, 3)

Column names: ['word', 'count', 'length']

Data types:
 word        str
count     int64
length    int64
dtype: object

Basic stats:
          count   length
count  5.00000  5.00000
mean   1.80000  6.00000
std    0.83666  2.44949
min    1.00000  2.00000
25%    1.00000  6.00000
50%    2.00000  6.00000
75%    2.00000  8.00000
max    3.00000  8.00000

First 3 rows:
      word  count  length
0      AI      3       2
1  Python      2       6
2  future      1       6


In [6]:
# Filtering means finding only the rows you care about
# Like searching for specific words in a document

# Show only words that appear more than once
frequent_words = df[df["count"] > 1]
print("Words appearing more than once:\n", frequent_words)

# Sort by count — highest first
sorted_df = df.sort_values("count", ascending=False)
print("\nSorted by frequency:\n", sorted_df)

Words appearing more than once:
        word  count  length
0        AI      3       2
1    Python      2       6
4  learning      2       8

Sorted by frequency:
        word  count  length
0        AI      3       2
1    Python      2       6
4  learning      2       8
2    future      1       6
3  language      1       8


In [7]:
# Now combine everything — NumPy + Pandas together
# This is exactly how your Document Assistant will process text

document_text = """
AI is transforming the world. Python is the language of AI.
Machine learning is a subset of AI. Deep learning is powerful.
Australia needs more AI engineers. Python developers are in demand.
"""

# Step 1 - split into words and clean
words = document_text.lower().replace(".", "").replace(",", "").split()

# Step 2 - count frequencies
word_count = {}
for word in words:
    word_count[word] = word_count.get(word, 0) + 1

# Step 3 - put into a DataFrame
df_doc = pd.DataFrame(list(word_count.items()), columns=["word", "count"])

# Step 4 - sort by most frequent
df_doc = df_doc.sort_values("count", ascending=False)

print("Top 10 most frequent words:\n")
print(df_doc.head(10))

Top 10 most frequent words:

           word  count
0            ai      4
1            is      4
3           the      2
5        python      2
9      learning      2
7            of      2
4         world      1
2  transforming      1
6      language      1
8       machine      1


In [4]:
import pandas as pd

# A DataFrame is like an Excel table in Python
# This is how we will store and analyze document data

data = {
    "word": ["AI", "Python", "future", "language", "learning"],
    "count": [3, 2, 1, 1, 2],
    "length": [2, 6, 6, 8, 8]
}

df = pd.DataFrame(data)
print(df)

       word  count  length
0        AI      3       2
1    Python      2       6
2    future      1       6
3  language      1       8
4  learning      2       8


In [1]:
import numpy as np

# Slicing means grabbing specific parts of an array
# Just like grabbing specific words from a document

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Full array:", arr)
print("First 3 elements:", arr[:3])
print("Last 3 elements:", arr[-3:])
print("Middle elements:", arr[2:6])
print("Every 2nd element:", arr[::2])

Full array: [ 10  20  30  40  50  60  70  80  90 100]
First 3 elements: [10 20 30]
Last 3 elements: [ 80  90 100]
Middle elements: [30 40 50 60]
Every 2nd element: [10 30 50 70 90]


In [2]:
# 2D arrays are like tables — rows and columns
# AI models store data exactly like this internally

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Full matrix:\n", matrix)
print("Shape:", matrix.shape)        # how many rows and columns
print("First row:", matrix[0])
print("Second column:", matrix[:, 1])
print("Single element row 1 col 2:", matrix[0][1])

Full matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
First row: [1 2 3]
Second column: [2 5 8]
Single element row 1 col 2: 2


In [3]:
# These operations are what AI uses to process data
# When AI reads your document, it does math like this on millions of numbers

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Add:", a + b)
print("Multiply:", a * b)
print("Square root:", np.sqrt(b))
print("Sum of all:", np.sum(b))
print("Mean:", np.mean(b))
print("Standard deviation:", np.std(b))

Add: [11 22 33 44 55]
Multiply: [ 10  40  90 160 250]
Square root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Sum of all: 150
Mean: 30.0
Standard deviation: 14.142135623730951


In [6]:
# A document is just a collection of words
# Lists and dictionaries are how we store and count them

sentence = "AI is the future and Python is the language of AI"

# Convert sentence into a list of words
words = sentence.split()
print("All words:", words)
print("Total words:", len(words))
print("Unique words:", len(set(words)))

All words: ['AI', 'is', 'the', 'future', 'and', 'Python', 'is', 'the', 'language', 'of', 'AI']
Total words: 11
Unique words: 8


In [7]:
# Count how many times each word appears
word_count = {}

for word in words:
    if word in word_count:
        word_count[word] += 1
    else:
        word_count[word] = 1

print(word_count)

{'AI': 2, 'is': 2, 'the': 2, 'future': 1, 'and': 1, 'Python': 1, 'language': 1, 'of': 1}


In [8]:
import numpy as np

# Convert counts into a NumPy array
counts = np.array(list(word_count.values()))
labels = np.array(list(word_count.keys()))

print("Words:", labels)
print("Counts:", counts)
print("Most repeated word appears:", np.max(counts), "times")
print("Average frequency:", np.mean(counts))

Words: ['AI' 'is' 'the' 'future' 'and' 'Python' 'language' 'of']
Counts: [2 2 2 1 1 1 1 1]
Most repeated word appears: 2 times
Average frequency: 1.375


In [9]:
# NumPy makes math on arrays super fast
numbers = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Max:", np.max(numbers))
print("Min:", np.min(numbers))

# Multiply every number by 2 in one line — no loop needed
print("Doubled:", numbers * 2)

Sum: 150
Mean: 30.0
Max: 50
Min: 10
Doubled: [ 20  40  60  80 100]


In [10]:
# This is the foundation of your AI Document Assistant
# Right now we are manually typing the text
# In Week 3 this will read a real PDF file automatically

document_text = """
Artificial intelligence is transforming the world. 
Python is the most popular language for AI development.
Machine learning and deep learning are subsets of AI.
Australia is investing heavily in AI and technology.
"""

words = document_text.lower().split()
print("Document has", len(words), "words")
print("Unique words:", len(set(words)))

Document has 32 words
Unique words: 26
